### GET All users:
GET http://localhost:8080/api/v1/users
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IldpbGxpc0BiYXRjYXZlLmNvbSIsImlhdCI6MTcwMjU0NzM4N30.hD91HgG16KwP3T-sVj0DrcasaG7hHiDdkCR0s9WuHn4


### Add a user:
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "name": {
    "first": "Bruce",
    "last": "Willis"
  },
  "address": {
    "street": "123 Main St",
    "city": "Anytown",
    "country": "Israel",
    "houseNumber": 20,
    "zip": "12345"
  },
  "image": {
    "alt": "user-profile",
    "url": "https://picsum.photos/200/300"
  },
  "phone": "050-8123091",
  "email": "Willis@batcave.com",
  "isBusiness": true,
  "password": "123456aA!"
}


### Login:
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "email": "Willis@batcave.com",
  "password": "123456aA!"
}