  ### GET All users:
GET http://localhost:8080/api/v1/users
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTcwMjgwMDg3Nn0.1UBbvM-gXol-pr21_FTWYARyVBYzwfMD9QLs8V8tA4o


### Add a user:
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "name": {
    "first": "root",
    "last": "admin"
  },
  "address": {
    "street": "123 Main St",
    "city": "Anytown",
    "country": "Israel",
    "houseNumber": 20,
    "zip": "12345"
  },
  "image": {
    "alt": "user-profile",
    "url": "https://picsum.photos/200/300"
  },
  "phone": "050-8123091",
  "email": "admin@gmail.com",
  "isBusiness": true,
  "password": "123456aA!" 
}


### Login:
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "email": "Willis@batcave.com",
  "password": "123456aA!"
}


### get Wayne by id with JWT of Willis:
GET http://localhost:8080/api/v1/users/65784e0a927be706a0d28789
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IldpbGxpc0BiYXRjYXZlLmNvbSIsImlhdCI6MTcwMjgwMDcwNn0.pZDlu6NmQdZhGH1ZDKK5dJAaRY-5S5Dvh3HY6Z4G1Eg


### GET Willis by id with jwt of Willis
GET http://localhost:8080/api/v1/users/65784e4a927be706a0d2878f
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IldpbGxpc0BiYXRjYXZlLmNvbSIsImlhdCI6MTcwMjgwMDcwNn0.pZDlu6NmQdZhGH1ZDKK5dJAaRY-5S5Dvh3HY6Z4G1Eg


### GET Wayne with JWT of admin:
GET http://localhost:8080/api/v1/users/65784e0a927be706a0d28789
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTcwMjgwMDg3Nn0.1UBbvM-gXol-pr21_FTWYARyVBYzwfMD9QLs8V8tA4o


### PUT Bruce Wayne with JWT of Wayne:
PUT http://localhost:8080/api/v1/users/65784e0a927be706a0d28789
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IldheW5lQGJhdGNhdmUuY29tIiwiaWF0IjoxNzAyODA3MzE4fQ.t2i7Kuyd4_HbuLqDUT0AWXy62v0zfXd8m5HIGP2nN2E
Content-Type: application/json

{
  "name": {
    "first": "Bruce!!!",
    "last": "Wayne!!!"
  },
  "address": {
    "street": "123 Main St",
    "city": "Anytown",
    "country": "Israel",
    "houseNumber": 20,
    "zip": "12345"
  },
  "image": {
    "alt": "user-profile",
    "url": "https://picsum.photos/200/300"
  },
  "phone": "050-8123091",
  "email": "Wayne@batcave.com",
  "isBusiness": true,
  "password": "123456aA!" 
}


### DELETE Bruce Wayne with JWT of Wayne:
DELETE http://localhost:8080/api/v1/users/65784e0a927be706a0d28789
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IldheW5lQGJhdGNhdmUuY29tIiwiaWF0IjoxNzAyODA3MzE4fQ.t2i7Kuyd4_HbuLqDUT0AWXy62v0zfXd8m5HIGP2nN2E


###
GET http://localhost:8080/api/v1/people

### add a card: ### new card
POST http://localhost:8080/api/v1/cards
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTcwMjk3NDMxNH0.9rxSVJKljg9si33a7qNMz-5wunk0CfmW7tjDLAQr8nk
Content-Type: application/json

{
    "title": "new card check likes",
    "subtitle": "new card ",
    "description": "new card description",
    "phone": "050-1234567",
    "email": "e@gamil.com",
    "web": "http://www.google.com",
    "address": {
        "city": "new city",
        "country": "new country",
        "street": "new street",
        "houseNumber": 21
    }
    
}


### Get all cards:
GET http://localhost:8080/api/v1/cards

### Get my-cards:
GET http://localhost:8080/api/v1/cards/my-cards
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTcwMjk3NDMxNH0.9rxSVJKljg9si33a7qNMz-5wunk0CfmW7tjDLAQr8nk


### GET Card by id:
GET http://localhost:8080/api/v1/cards/658154e8a41b0c0ac526cfc6