### GET all users:
GET http://localhost:5500/users

### GET - search a user:
GET http://localhost:5500/search?firstName=john

### POST - add a user:
POST http://localhost:5500/users
Content-Type: application/json

{
   "firstName":"Bruce", 
   "lastName": "Wayne"
}